version: '3.8'

services:
  # Main application (already exists in main docker-compose.yml)
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/aisocial
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker for task processing
  celery-worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/aisocial
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: celery -A backend.tasks.celery_app worker --loglevel=info --queues=autonomous,reports,metrics,posting,legacy

  # Celery Beat for scheduled tasks
  celery-beat:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/aisocial
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - celery-beat-data:/app/celerybeat-schedule
    command: celery -A backend.tasks.celery_app beat --loglevel=info --schedule=/app/celerybeat-schedule

  # Celery Flower for monitoring (optional)
  celery-flower:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: celery -A backend.tasks.celery_app flower --port=5555

  # PostgreSQL Database
  db:
    image: pgvector/pgvector:pg15
    environment:
      - POSTGRES_DB=aisocial
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: postgres -c shared_preload_libraries=vector

  # Redis for Celery broker and result backend
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
  celery-beat-data: